package com.kodilla.frontend.domain;

public enum Manufacturer {
    ALFA_ROMEO, AUDI, BMW, CHEVROLET, CHRYSLER, CITROEN, DACIA, FIAT, FORD, HONDA, HYUNDAI,
    INFINITI, JAGUAR, JEEP, KIA, LANCIA, LAND_ROVER, LEXUS, MINI, MAZDA, MERCEDES_BENZ, MITSUBISHI, NISSAN,
    OPEL, PEUGEOT, PORSCHE, RENAULT, SEAT, SAAB, SKODA, SSANGYONG, SUBARU, SUZUKI, TOYOTA, VOLKSWAGEN, VOLVO
}
